# **Importing the necessary files required for analysis**

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

ModuleNotFoundError: No module named 'pandas'

In [ ]:
sales = "/content/drive/MyDrive/Milk/sales.csv"
product_costs= "/content/drive/MyDrive/Milk/product_costs.csv"
milk = "/content/drive/MyDrive/Milk/milk_collections.csv"
spoilage = "/content/drive/MyDrive/Milk/spoilage_loss_estimation.csv"
profit = "/content/drive/MyDrive/Milk/profit_table.csv"

sales = pd.read_csv(sales)
product_costs = pd.read_csv(product_costs)
milk = pd.read_csv(milk)
spoilage = pd.read_csv(spoilage)
profit = pd.read_csv(profit)

**Getting the basic Overview of the Data and its Datatypes.**

In [ ]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   sale_id         300000 non-null  int64
 1   date            300000 non-null  object
 2   region          300000 non-null  object
 3   product_name    300000 non-null  object
 4   units_sold      300000 non-null  int64
 5   promotion_flag  300000 non-null  int64
 6   price_per_unit  300000 non-null  int64
 7   revenue         300000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 18.3+ MB

In [ ]:
product_costs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   product_name          8 non-null      object
 1   mrp                   8 non-null      int64
 2   base_production_cost  8 non-null      int64
 3   packaging_cost        8 non-null      float64
 4   total_cost_per_unit   8 non-null      float64
dtypes: float64(2), int64(2), object(1)
memory usage: 452.0+ bytes

In [ ]:
profit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 15 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   sale_id               300000 non-null  int64
 1   date                  300000 non-null  object
 2   region                300000 non-null  object
 3   product_name          300000 non-null  object
 4   units_sold            300000 non-null  int64
 5   promotion_flag        300000 non-null  int64
 6   price_per_unit        300000 non-null  int64
 7   revenue               300000 non-null  int64
 8   mrp                   300000 non-null  int64
 9   base_production_cost  300000 non-null  int64
 10  packaging_cost        300000 non-null  float64
 11  total_cost_per_unit   300000 non-null  float64
 12  total_cost            300000 non-null  float64
 13  profit                300000 non-null  float64
 14  profit_margin_pct     300000 non-null  float64
dtypes: float64(5), int64(7), object(3)
memory usage: 34.3+ MB

In [ ]:
milk.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 9 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   collection_id             200000 non-null  int64
 1   date                      200000 non-null  object
 2   supplier_id               200000 non-null  int64
 3   village                   200000 non-null  object
 4   liters_collected          200000 non-null  float64
 5   fat_percent               200000 non-null  float64
 6   snf_percent               200000 non-null  float64
 7   temperature_on_arrival_c  200000 non-null  float64
 8   quality_grade             200000 non-null  object
dtypes: float64(4), int64(2), object(3)
memory usage: 13.7+ MB

In [ ]:
spoilage.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 10 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   collection_id             200000 non-null  int64
 1   date                      200000 non-null  object
 2   supplier_id               200000 non-null  int64
 3   village                   200000 non-null  object
 4   liters_collected          200000 non-null  float64
 5   temperature_on_arrival_c  200000 non-null  float64
 6   quality_grade             200000 non-null  object
 7   spoilage_rate             200000 non-null  float64
 8   spoiled_liters            200000 non-null  float64
 9   loss_amount_rs            200000 non-null  float64
dtypes: float64(5), int64(2), object(3)
memory usage: 15.3+ MB

In [ ]:
sales.head(10)

,sale_id,date,region,product_name,units_sold,promotion_flag,price_per_unit,revenue
0,1,15/09/2024,Rajasthan,Milk 500ml,43,1,28,1204
1,2,4/02/2024,Rajasthan,Butter 100g,13,1,52,676
2,3,14/06/2024,Maharashtra,Curd 500g,40,1,35,1400
3,4,16/07/2024,Maharashtra,Paneer 200g,18,0,85,1530
4,5,28/06/2024,Maharashtra,Paneer 200g,26,0,85,2210
5,6,27/09/2024,UP,Ghee 500ml,24,1,280,6720
6,7,18/11/2024,UP,Curd 500g,20,0,35,700
7,8,17/07/2024,Gujarat,Milk 1L,5,0,54,270
8,9,29/11/2024,Rajasthan,Milk 1L,3,1,54,162
9,10,12/11/2024,Delhi,Butter 200g,17,0,104,1768

In [ ]:
milk.head(7)

,collection_id,date,supplier_id,village,liters_collected,fat_percent,snf_percent,temperature_on_arrival_c,quality_grade
0,1,12/04/2024,3952,Surendranagar,9.31,4.15,8.46,36.7,High
1,2,14/12/2024,3763,Anand,11.09,3.50,8.76,33.8,Low
2,3,27/09/2024,2202,Nadiad,3.67,5.44,7.95,12.0,Low
3,4,16/04/2024,1917,Rajkot,11.57,6.81,8.67,27.9,High
4,5,12/03/2024,1223,Nadiad,16.37,3.36,8.42,31.4,Medium
5,6,7/07/2024,1780,Nadiad,21.66,5.48,7.59,14.3,Medium
6,7,21/01/2024,4238,Anand,7.30,4.83,8.89,11.9,Medium

In [ ]:
spoilage.head(10)

,collection_id,date,supplier_id,village,liters_collected,temperature_on_arrival_c,quality_grade,spoilage_rate,spoiled_liters,loss_amount_rs
0,1,12/04/2024,3952,Surendranagar,9.31,36.7,High,0.10,0.93,29.76
1,2,14/12/2024,3763,Anand,11.09,33.8,Low,0.18,2.00,64.00
2,3,27/09/2024,2202,Nadiad,3.67,12.0,Low,0.13,0.48,15.36
3,4,16/04/2024,1917,Rajkot,11.57,27.9,High,0.10,1.16,37.12
4,5,12/03/2024,1223,Nadiad,16.37,31.4,Medium,0.13,2.13,68.16
5,6,7/07/2024,1780,Nadiad,21.66,14.3,Medium,0.08,1.73,55.36
6,7,21/01/2024,4238,Anand,7.30,11.9,Medium,0.08,0.58,18.56
7,8,12/04/2024,4123,Rajkot,10.17,32.1,Medium,0.13,1.32,42.24
8,9,1/05/2024,2257,Vadodara,15.14,6.5,Medium,0.05,0.76,24.32
9,10,2/08/2024,4771,Rajkot,12.85,16.1,High,0.05,0.64,20.48

In [ ]:
profit.head(10)

,sale_id,date,region,product_name,units_sold,promotion_flag,price_per_unit,revenue,mrp,base_production_cost,packaging_cost,total_cost_per_unit,total_cost,profit,profit_margin_pct
0,1,15/09/2024,Rajasthan,Milk 500ml,43,1,28,1204,28,20,1.84,21.84,939.12,264.88,-1.71
1,2,4/02/2024,Rajasthan,Butter 100g,13,1,52,676,52,38,3.47,41.47,539.11,136.89,-8.50
2,3,14/06/2024,Maharashtra,Curd 500g,40,1,35,1400,35,25,5.90,30.90,1236.00,164.00,-17.57
3,4,16/07/2024,Maharashtra,Paneer 200g,18,0,85,1530,85,65,3.92,68.92,1240.56,289.44,6.94
4,5,28/06/2024,Maharashtra,Paneer 200g,26,0,85,2210,85,65,3.92,68.92,1791.92,418.08,6.94
5,6,27/09/2024,UP,Ghee 500ml,24,1,280,6720,280,210,3.76,213.76,5130.24,1589.76,21.19
6,7,18/11/2024,UP,Curd 500g,20,0,35,700,35,25,5.90,30.90,618.00,82.00,-17.57
7,8,17/07/2024,Gujarat,Milk 1L,5,0,54,270,54,40,5.01,45.01,225.05,44.95,-2.17
8,9,29/11/2024,Rajasthan,Milk 1L,3,1,54,162,54,40,5.01,45.01,135.03,26.97,-2.17
9,10,12/11/2024,Delhi,Butter 200g,17,0,104,1768,104,76,4.76,80.76,1372.92,395.08,13.12

In [ ]:
product_costs.head(10)

,product_name,mrp,base_production_cost,packaging_cost,total_cost_per_unit
0,Milk 500ml,28,20,1.84,21.84
1,Milk 1L,54,40,5.01,45.01
2,Butter 100g,52,38,3.47,41.47
3,Butter 200g,104,76,4.76,80.76
4,Curd 500g,35,25,5.90,30.90
5,Paneer 200g,85,65,3.92,68.92
6,Ghee 500ml,280,210,3.76,213.76
7,Ice Cream 100ml,40,28,1.82,29.82

**Cleaning the Raw data to make it more readable and understandable.**

In [ ]:
sales.isnull().sum()

sale_id           0
date              0
region            0
product_name      0
units_sold        0
promotion_flag    0
price_per_unit    0
revenue           0
dtype: int64

In [ ]:
# Checking for any duplicates and removing them if any.
print("Before:", sales.shape)

sales = sales.drop_duplicates()

print("After:", sales.shape)

Before: (300000, 8)
After: (300000, 8)

In [ ]:
# Fixing the Date Format
sales['date'] = pd.to_datetime(sales['date'], dayfirst=True, errors='coerce')

print(sales['date'].isnull().sum())

0

In [ ]:
sales = sales.dropna(subset=['date'])

In [ ]:
sales = sales[sales['units_sold'] > 0]
sales = sales[sales['revenue'] > 0]

In [ ]:
sales['product_name'] = sales['product_name'].str.lower().str.strip()

In [ ]:
sales.head(5)

,sale_id,date,region,product_name,units_sold,promotion_flag,price_per_unit,revenue
0,1,2024-09-15,Rajasthan,milk 500ml,43,1,28,1204
1,2,2024-02-04,Rajasthan,butter 100g,13,1,52,676
2,3,2024-06-14,Maharashtra,curd 500g,40,1,35,1400
3,4,2024-07-16,Maharashtra,paneer 200g,18,0,85,1530
4,5,2024-06-28,Maharashtra,paneer 200g,26,0,85,2210

In [ ]:
product_costs['product_name'].duplicated().sum()

np.int64(0)

In [ ]:
product_costs = product_costs.drop_duplicates(subset=['product_name'])

In [ ]:
product_costs = product_costs[product_costs['base_production_cost'] > 0]

In [ ]:
product_costs['product_name'] = product_costs['product_name'].str.lower().str.strip()

In [ ]:
product_costs.head(5)

  product_name  mrp  base_production_cost  packaging_cost  total_cost_per_unit
0   milk 500ml   28                    20            1.84                21.84
1      milk 1l   54                    40            5.01                45.01
2  butter 100g   52                    38            3.47                41.47
3  butter 200g  104                    76            4.76                80.76
4    curd 500g   35                    25            5.90                30.90

In [ ]:
milk.isnull().sum()

collection_id               0
date                        0
supplier_id                 0
village                     0
liters_collected            0
fat_percent                 0
snf_percent                 0
temperature_on_arrival_c    0
quality_grade               0
dtype: int64

In [ ]:
milk.isnull().sum()

collection_id               0
date                        0
supplier_id                 0
village                     0
liters_collected            0
fat_percent                 0
snf_percent                 0
temperature_on_arrival_c    0
quality_grade               0
dtype: int64

In [ ]:
# Milk fat percent cannot be low than 15%.
milk = milk[milk['fat_percent'] <= 15]

In [ ]:
# remove negative quantity liters.
milk = milk[milk['liters_collected'] > 0]

In [ ]:
milk['date'] = pd.to_datetime(milk['date'], dayfirst=True)

In [ ]:
milk.head(5)

,collection_id,date,supplier_id,village,liters_collected,fat_percent,snf_percent,temperature_on_arrival_c,quality_grade
0,1,2024-04-12,3952,Surendranagar,9.31,4.15,8.46,36.7,High
1,2,2024-12-14,3763,Anand,11.09,3.50,8.76,33.8,Low
2,3,2024-09-27,2202,Nadiad,3.67,5.44,7.95,12.0,Low
3,4,2024-04-16,1917,Rajkot,11.57,6.81,8.67,27.9,High
4,5,2024-03-12,1223,Nadiad,16.37,3.36,8.42,31.4,Medium

In [ ]:
spoilage = spoilage[spoilage['spoiled_liters'] >= 0]

In [ ]:
invalid_ids = spoilage[~spoilage['collection_id'].isin(milk['collection_id'])]

In [ ]:
spoilage = spoilage[spoilage['collection_id'].isin(milk['collection_id'])]

In [ ]:
spoilage.head(5)

,collection_id,date,supplier_id,village,liters_collected,temperature_on_arrival_c,quality_grade,spoilage_rate,spoiled_liters,loss_amount_rs
0,1,12/04/2024,3952,Surendranagar,9.31,36.7,High,0.10,0.93,29.76
1,2,14/12/2024,3763,Anand,11.09,33.8,Low,0.18,2.00,64.00
2,3,27/09/2024,2202,Nadiad,3.67,12.0,Low,0.13,0.48,15.36
3,4,16/04/2024,1917,Rajkot,11.57,27.9,High,0.10,1.16,37.12
4,5,12/03/2024,1223,Nadiad,16.37,31.4,Medium,0.13,2.13,68.16

In [ ]:
profit = profit[profit['profit'] >= 0]

In [ ]:
profit['date'] = pd.to_datetime(profit['date'], dayfirst=True)

In [ ]:
invalid_sales = profit[~profit['sale_id'].isin(sales['sale_id'])]
invalid_sales.head()

Empty DataFrame
Columns: [sale_id, date, region, product_name, units_sold, promotion_flag, price_per_unit, revenue, mrp, base_production_cost, packaging_cost, total_cost_per_unit, total_cost, profit, profit_margin_pct]
Index: []

In [ ]:
profit.head(5)

,sale_id,date,region,product_name,units_sold,promotion_flag,price_per_unit,revenue,mrp,base_production_cost,packaging_cost,total_cost_per_unit,total_cost,profit,profit_margin_pct
0,1,2024-09-15,Rajasthan,Milk 500ml,43,1,28,1204,28,20,1.84,21.84,939.12,264.88,-1.71
1,2,2024-02-04,Rajasthan,Butter 100g,13,1,52,676,52,38,3.47,41.47,539.11,136.89,-8.50
2,3,2024-06-14,Maharashtra,Curd 500g,40,1,35,1400,35,25,5.90,30.90,1236.00,164.00,-17.57
3,4,2024-07-16,Maharashtra,Paneer 200g,18,0,85,1530,85,65,3.92,68.92,1240.56,289.44,6.94
4,5,2024-06-28,Maharashtra,Paneer 200g,26,0,85,2210,85,65,3.92,68.92,1791.92,418.08,6.94

In [ ]:
merged = pd.merge(sales, product_costs, on='product_name', how='left')
merged.head()

,sale_id,date,region,product_name,units_sold,promotion_flag,price_per_unit,revenue,mrp,base_production_cost,packaging_cost,total_cost_per_unit
0,1,2024-09-15,Rajasthan,milk 500ml,43,1,28,1204,28,20,1.84,21.84
1,2,2024-02-04,Rajasthan,butter 100g,13,1,52,676,52,38,3.47,41.47
2,3,2024-06-14,Maharashtra,curd 500g,40,1,35,1400,35,25,5.90,30.90
3,4,2024-07-16,Maharashtra,paneer 200g,18,0,85,1530,85,65,3.92,68.92
4,5,2024-06-28,Maharashtra,paneer 200g,26,0,85,2210,85,65,3.92,68.92

In [ ]:
sales_product = pd.merge(
    sales,
    product_costs,
    on="product_name",
    how="inner"
)

sales_product["total_cost"] = sales_product["units_sold"] * sales_product["total_cost_per_unit"]
sales_product["calculated_profit"] = sales_product["revenue"] - sales_product["total_cost"]

sales_product.head()

,sale_id,date,region,product_name,units_sold,promotion_flag,price_per_unit,revenue,mrp,base_production_cost,packaging_cost,total_cost_per_unit,total_cost,calculated_profit
0,1,2024-09-15,Rajasthan,milk 500ml,43,1,28,1204,28,20,1.84,21.84,939.12,264.88
1,2,2024-02-04,Rajasthan,butter 100g,13,1,52,676,52,38,3.47,41.47,539.11,136.89
2,3,2024-06-14,Maharashtra,curd 500g,40,1,35,1400,35,25,5.90,30.90,1236.00,164.00
3,4,2024-07-16,Maharashtra,paneer 200g,18,0,85,1530,85,65,3.92,68.92,1240.56,289.44
4,5,2024-06-28,Maharashtra,paneer 200g,26,0,85,2210,85,65,3.92,68.92,1791.92,418.08

In [ ]:
left_check = pd.merge(
    sales,
    product_costs,
    on="product_name",
    how="left",
    indicator=True
)

missing_products = left_check[left_check["_merge"] == "left_only"]
missing_products.head()

Empty DataFrame
Columns: [sale_id, date, region, product_name, units_sold, promotion_flag, price_per_unit, revenue, mrp, base_production_cost, packaging_cost, total_cost_per_unit, _merge]
Index: []

In [ ]:
print(sales.columns)
print(product_costs.columns)
print(profit.columns)

Index(['sale_id', 'date', 'region', 'product_name', 'units_sold',
       'promotion_flag', 'price_per_unit', 'revenue'],
      dtype='object')
Index(['product_name', 'mrp', 'base_production_cost', 'packaging_cost',
       'total_cost_per_unit'],
      dtype='object')
Index(['sale_id', 'date', 'region', 'product_name', 'units_sold',
       'promotion_flag', 'price_per_unit', 'revenue', 'mrp',
       'base_production_cost', 'packaging_cost', 'total_cost_per_unit',
       'total_cost', 'profit', 'profit_margin_pct'],
      dtype='object')

In [ ]:
sales_cost = sales.merge(product_costs, on="product_name")

sales_cost["calculated_total_cost"] = (
    sales_cost["units_sold"] *
    sales_cost["total_cost_per_unit"]
)

sales_cost["calculated_profit"] = (
    sales_cost["revenue"] -
    sales_cost["calculated_total_cost"]
)

sales_cost.head()

,sale_id,date,region,product_name,units_sold,promotion_flag,price_per_unit,revenue,mrp,base_production_cost,packaging_cost,total_cost_per_unit,calculated_total_cost,calculated_profit
0,1,2024-09-15,Rajasthan,milk 500ml,43,1,28,1204,28,20,1.84,21.84,939.12,264.88
1,2,2024-02-04,Rajasthan,butter 100g,13,1,52,676,52,38,3.47,41.47,539.11,136.89
2,3,2024-06-14,Maharashtra,curd 500g,40,1,35,1400,35,25,5.90,30.90,1236.00,164.00
3,4,2024-07-16,Maharashtra,paneer 200g,18,0,85,1530,85,65,3.92,68.92,1240.56,289.44
4,5,2024-06-28,Maharashtra,paneer 200g,26,0,85,2210,85,65,3.92,68.92,1791.92,418.08

In [ ]:
region_dashboard = (
    profit
    .groupby("region")
    .agg({
        "revenue": "sum",
        "profit": "sum",
        "units_sold": "sum"
    })
    .reset_index()
)

region_dashboard["profit_margin_%"] = (
    region_dashboard["profit"] /
    region_dashboard["revenue"]
) * 100

region_dashboard

        region    revenue       profit  units_sold  profit_margin_%
0        Delhi  105788082  22690707.78     1249634        21.449210
1      Gujarat  105799646  22706612.03     1249827        21.461898
2           MP  105648186  22692239.16     1247249        21.479062
3  Maharashtra  105918743  22738959.96     1248580        21.468306
4    Rajasthan  106068216  22774182.05     1248790        21.471260
5           UP  106778638  22930222.77     1257655        21.474541

In [ ]:
promotion_dashboard = (
    sales
    .groupby("promotion_flag")
    .agg({
        "revenue": "sum",
        "units_sold": "sum"
    })
    .reset_index()
)

promotion_dashboard

   promotion_flag    revenue  units_sold
0               0  444652550     5240152
1               1  191348961     2261583

In [ ]:
sales["date"] = pd.to_datetime(sales["date"], dayfirst=True)
profit["date"] = pd.to_datetime(profit["date"], dayfirst=True)

sales["month"] = sales["date"].dt.to_period("M")
profit["month"] = profit["date"].dt.to_period("M")

monthly = (
    sales.groupby("month")["revenue"].sum()
    .reset_index()
    .merge(
        profit.groupby("month")["profit"].sum().reset_index(),
        on="month"
    )
)

monthly

      month   revenue       profit
0   2024-01  54740999  11769767.10
1   2024-02  50424869  10833435.80
2   2024-03  54124190  11622038.92
3   2024-04  52990575  11373371.42
4   2024-05  53701681  11527853.99
5   2024-06  52532583  11274654.87
6   2024-07  53666520  11534983.88
7   2024-08  53629621  11506775.92
8   2024-09  52745621  11330350.74
9   2024-10  53819333  11531643.14
10  2024-11  51906078  11147404.80
11  2024-12  51719441  11080643.17

In [ ]:
product_profit = (
    profit
    .groupby("product_name")["profit"]
    .sum()
    .reset_index()
)

total_profit = product_profit["profit"].sum()

product_profit["contribution_%"] = (
    product_profit["profit"] / total_profit
) * 100

product_profit.sort_values("contribution_%", ascending=False).head(5)

      product_name       profit  contribution_%
3       Ghee 500ml  62117951.04       45.496683
1      Butter 200g  21885224.20       16.029265
7      Paneer 200g  15049079.04       11.022308
0      Butter 100g   9898020.99        7.249549
4  Ice Cream 100ml   9614053.08        7.041564

In [ ]:
cost_structure = product_costs.copy()

cost_structure["total_variable_cost"] = (
    cost_structure["base_production_cost"] +
    cost_structure["packaging_cost"]
)

cost_structure[[
    "product_name",
    "base_production_cost",
    "packaging_cost",
    "total_variable_cost",
    "total_cost_per_unit"
]]

,product_name,base_production_cost,packaging_cost,total_variable_cost,total_cost_per_unit
0,milk 500ml,20,1.84,21.84,21.84
1,milk 1l,40,5.01,45.01,45.01
2,butter 100g,38,3.47,41.47,41.47
3,butter 200g,76,4.76,80.76,80.76
4,curd 500g,25,5.90,30.90,30.90
5,paneer 200g,65,3.92,68.92,68.92
6,ghee 500ml,210,3.76,213.76,213.76
7,ice cream 100ml,28,1.82,29.82,29.82

In [ ]:
efficiency = (
    sales
    .groupby("product_name")
    .agg({
        "revenue": "sum",
        "units_sold": "sum"
    })
    .reset_index()
)

efficiency["revenue_per_unit"] = (
    efficiency["revenue"] /
    efficiency["units_sold"]
)

efficiency.sort_values("revenue_per_unit", ascending=False)

      product_name    revenue  units_sold  revenue_per_unit
3       ghee 500ml  262575880      937771             280.0
1      butter 200g   97937320      941705             104.0
7      paneer 200g   79550480      935888              85.0
5          milk 1l   50387940      933110              54.0
0      butter 100g   48879116      939983              52.0
4  ice cream 100ml   37776240      944406              40.0
2        curd 500g   32830595      938017              35.0
6       milk 500ml   26063940      930855              28.0

In [ ]:
profit_cost = (
    profit
    .groupby("product_name")
    .agg({
        "profit": "sum",
        "total_cost": "sum"
    })
    .reset_index()
)

profit_cost["profit_cost_ratio"] = (
    profit_cost["profit"] /
    profit_cost["total_cost"]
)

profit_cost.sort_values("profit_cost_ratio", ascending=False)

      product_name       profit    total_cost  profit_cost_ratio
4  Ice Cream 100ml   9614053.08  2.816219e+07           0.341382
3       Ghee 500ml  62117951.04  2.004579e+08           0.309880
1      Butter 200g  21885224.20  7.605210e+07           0.287766
6       Milk 500ml   5734066.80  2.032987e+07           0.282051
0      Butter 100g   9898020.99  3.898110e+07           0.253918
7      Paneer 200g  15049079.04  6.450140e+07           0.233314
5          Milk 1L   8388658.90  4.199928e+07           0.199733
2        Curd 500g   3845869.70  2.898473e+07           0.132686

In [ ]:
monthly["previous_revenue"] = monthly["revenue"].shift(1)

monthly["growth_%"] = (
    (monthly["revenue"] - monthly["previous_revenue"]) /
    monthly["previous_revenue"]
) * 100

monthly

      month   revenue       profit  previous_revenue  growth_%
0   2024-01  54740999  11769767.10               NaN       NaN
1   2024-02  50424869  10833435.80        54740999.0 -7.884639
2   2024-03  54124190  11622038.92        50424869.0  7.336303
3   2024-04  52990575  11373371.42        54124190.0 -2.094470
4   2024-05  53701681  11527853.99        52990575.0  1.341948
5   2024-06  52532583  11274654.87        53701681.0 -2.177023
6   2024-07  53666520  11534983.88        52532583.0  2.158540
7   2024-08  53629621  11506775.92        53666520.0 -0.068756
8   2024-09  52745621  11330350.74        53629621.0 -1.648343
9   2024-10  53819333  11531643.14        52745621.0  2.035642
10  2024-11  51906078  11147404.80        53819333.0 -3.554959
11  2024-12  51719441  11080643.17        51906078.0 -0.359567

In [ ]:
print(milk.columns)
print(spoilage.columns)

Index(['collection_id', 'date', 'supplier_id', 'village', 'liters_collected',
       'fat_percent', 'snf_percent', 'temperature_on_arrival_c',
       'quality_grade'],
      dtype='object')
Index(['collection_id', 'date', 'supplier_id', 'village', 'liters_collected',
       'temperature_on_arrival_c', 'quality_grade', 'spoilage_rate',
       'spoiled_liters', 'loss_amount_rs'],
      dtype='object')

**KPI calculation**

In [ ]:
# Merge sales + cost
df = sales.merge(product_costs, on="product_name")

df["date"] = pd.to_datetime(df["date"], dayfirst=True, errors="coerce")
spoilage["date"] = pd.to_datetime(spoilage["date"], dayfirst=True, errors="coerce")

# Calculate cost & gross profit
df["total_cost"] = df["units_sold"] * df["total_cost_per_unit"]
df["gross_profit"] = df["revenue"] - df["total_cost"]

# Merge spoilage by date
spoilage_loss = spoilage.groupby("date")["loss_amount_rs"].sum().reset_index()

df = df.merge(spoilage_loss, on="date", how="left")
df["loss_amount_rs"] = df["loss_amount_rs"].fillna(0)

df["true_net_profit"] = df["gross_profit"] - df["loss_amount_rs"]

kpi = df["true_net_profit"].sum()

print("True Net Profit After Spoilage:", round(kpi,2))

True Net Profit After Spoilage: -5320188730.33

In [ ]:

# -----------------------------
# 2️⃣ Standardize Date Columns
# -----------------------------
sales["date"] = pd.to_datetime(sales["date"], dayfirst=True, errors="coerce")
milk["date"] = pd.to_datetime(milk["date"], dayfirst=True, errors="coerce")
spoilage["date"] = pd.to_datetime(spoilage["date"], dayfirst=True, errors="coerce")

# -----------------------------
# 3️⃣ Merge Sales + Product Costs
# -----------------------------
df = sales.merge(product_costs, on="product_name", how="left")

# -----------------------------
# 4️⃣ Calculate Cost & Gross Profit
# -----------------------------
df["total_cost"] = df["units_sold"] * df["total_cost_per_unit"]
df["gross_profit"] = df["revenue"] - df["total_cost"]

# -----------------------------
# 5️⃣ Aggregate Sales to Daily Level
# -----------------------------
sales_daily = df.groupby("date").agg(
    total_revenue=("revenue", "sum"),
    total_cost=("total_cost", "sum"),
    gross_profit=("gross_profit", "sum")
).reset_index()

# -----------------------------
# 6️⃣ Aggregate Spoilage to Daily Level
# -----------------------------
spoilage_daily = spoilage.groupby("date").agg(
    total_spoilage_loss=("loss_amount_rs", "sum"),
    total_spoiled_liters=("spoiled_liters", "sum")
).reset_index()

# -----------------------------
# 7️⃣ Aggregate Milk Collection
# -----------------------------
milk_daily = milk.groupby("date").agg(
    total_liters_collected=("liters_collected", "sum"),
    avg_fat_percent=("fat_percent", "mean"),
    avg_snf_percent=("snf_percent", "mean")
).reset_index()

# -----------------------------
# 8️⃣ Merge All Daily KPIs
# -----------------------------
final_kpi = sales_daily.merge(spoilage_daily, on="date", how="left")
final_kpi = final_kpi.merge(milk_daily, on="date", how="left")

# Replace missing spoilage with 0
final_kpi["total_spoilage_loss"] = final_kpi["total_spoilage_loss"].fillna(0)
final_kpi["total_spoiled_liters"] = final_kpi["total_spoiled_liters"].fillna(0)

# -----------------------------
# 9️⃣ Calculate Final Net KPI
# -----------------------------
final_kpi["net_profit"] = final_kpi["gross_profit"] - final_kpi["total_spoilage_loss"]
final_kpi["profit_margin_pct"] = (
    final_kpi["net_profit"] / final_kpi["total_revenue"]
) * 100

# -----------------------------
# 🔟 Final Output (ONE TABLE)
# -----------------------------
print(final_kpi.head())

# If you want summary KPI:
print("\n====== OVERALL BUSINESS KPI ======")
print("Total Revenue:", final_kpi["total_revenue"].sum())
print("Total Cost:", final_kpi["total_cost"].sum())
print("Total Gross Profit:", final_kpi["gross_profit"].sum())
print("Total Spoilage Loss:", final_kpi["total_spoilage_loss"].sum())
print("Final Net Profit:", final_kpi["net_profit"].sum())

        date  total_revenue  total_cost  gross_profit  total_spoilage_loss  \
0 2024-01-01        1801686  1413446.77     388239.23             18647.04
1 2024-01-02        1742957  1369827.94     373129.06             18289.60
2 2024-01-03        1817050  1426105.92     390944.08             17567.04
3 2024-01-04        1664617  1306994.70     357622.30             18241.60
4 2024-01-05        1734000  1361219.93     372780.07             18724.16

   total_spoiled_liters  total_liters_collected  avg_fat_percent  \
0                582.72                 5581.67         5.012218
1                571.55                 5546.39         4.996109
2                548.97                 5325.84         4.960227
3                570.05                 5477.17         5.040509
4                585.13                 5445.84         4.975824

   avg_snf_percent  net_profit  profit_margin_pct
0         8.480092   369592.19          20.513685
1         8.496400   354839.46          20.358475
2         8.490416   373377.04          20.548529
3         8.518600   339380.70          20.387915
4         8.554551   354055.91          20.418449

====== OVERALL BUSINESS KPI ======
Total Revenue: 636001511
Total Cost: 499468587.25
Total Gross Profit: 136532923.75
Total Spoilage Loss: 6638241.6
Final Net Profit: 129894682.15000002

In [ ]:
overall_margin = (
    final_kpi["net_profit"].sum() / df["revenue"].sum()
) * 100

print("Overall Profit Margin %:", round(overall_margin, 2))

Overall Profit Margin %: 20.42

In [ ]:
cost_efficiency = df["total_cost"].sum() / df["revenue"].sum()
print("Cost Efficiency Ratio:", round(cost_efficiency,3))

Cost Efficiency Ratio: 0.785

In [ ]:
total_loss = spoilage["loss_amount_rs"].sum()
total_revenue = sales["revenue"].sum()

impact_pct = (total_loss / total_revenue) * 100
print("Spoilage Impact % on Revenue:", round(impact_pct,2))

Spoilage Impact % on Revenue: 1.04

In [ ]:
total_liters = milk["liters_collected"].sum()
total_revenue = sales["revenue"].sum()

print("Revenue per Liter:", round(total_revenue / total_liters,2))

Revenue per Liter: 318.21

In [ ]:
supplier_loss = spoilage.groupby("supplier_id")["loss_amount_rs"].sum().reset_index()
print(supplier_loss.sort_values("loss_amount_rs", ascending=False).head())

      supplier_id  loss_amount_rs
737          1737         2708.48
150          1150         2695.36
2180         3180         2627.20
2471         3471         2576.96
3572         4572         2576.64

In [ ]:
promo_df = df.groupby("promotion_flag").agg({
    "revenue": "sum",
    "gross_profit": "sum"
}).reset_index()

promo_df["ROI"] = promo_df["gross_profit"] / promo_df["revenue"]

print(promo_df)

   promotion_flag    revenue  gross_profit       ROI
0               0  444652550   95475883.34  0.214720
1               1  191348961   41057040.41  0.214566

In [ ]:
quality_kpi = milk.groupby("village").agg({
    "fat_percent":"mean",
    "snf_percent":"mean"
}).reset_index()

print(quality_kpi.sort_values("fat_percent", ascending=False).head())

         village  fat_percent  snf_percent
3       Palanpur     5.013759     8.494757
0          Anand     5.010662     8.495564
2         Nadiad     5.007586     8.502443
5  Surendranagar     5.002656     8.493873
4         Rajkot     4.998511     8.502987

In [ ]:
temp_loss = spoilage.groupby("temperature_on_arrival_c")["loss_amount_rs"].mean()
print(temp_loss.sort_values(ascending=False).head())

temperature_on_arrival_c
37.2    44.221765
23.4    44.042955
21.6    43.978978
33.8    43.898234
25.1    43.865961
Name: loss_amount_rs, dtype: float64

In [ ]:
product_kpi = df.groupby("product_name")["gross_profit"].sum().reset_index()
print(product_kpi.sort_values("gross_profit", ascending=False))

      product_name  gross_profit
3       ghee 500ml   62117951.04
1      butter 200g   21885224.20
7      paneer 200g   15049079.04
0      butter 100g    9898020.99
4  ice cream 100ml    9614053.08
5          milk 1l    8388658.90
6       milk 500ml    5734066.80
2        curd 500g    3845869.70

In [ ]:
region_kpi = df.groupby("region")["gross_profit"].sum().reset_index()
print(region_kpi.sort_values("gross_profit", ascending=False))

        region  gross_profit
5           UP   22930222.77
4    Rajasthan   22774182.05
3  Maharashtra   22738959.96
1      Gujarat   22706612.03
2           MP   22692239.16
0        Delhi   22690707.78

In [ ]:
liters_sold_estimate = sales["units_sold"].sum()

utilization_ratio = liters_sold_estimate / total_liters
print("Milk Utilization Ratio:", round(utilization_ratio,2))

Milk Utilization Ratio: 3.75

In [ ]:
product_costs["cost_variance"] = product_costs["mrp"] - product_costs["total_cost_per_unit"]
print(product_costs.sort_values("cost_variance", ascending=False))

      product_name  mrp  base_production_cost  packaging_cost  \
6       ghee 500ml  280                   210            3.76
3      butter 200g  104                    76            4.76
5      paneer 200g   85                    65            3.92
2      butter 100g   52                    38            3.47
7  ice cream 100ml   40                    28            1.82
1          milk 1l   54                    40            5.01
0       milk 500ml   28                    20            1.84
4        curd 500g   35                    25            5.90

   total_cost_per_unit  cost_variance
6               213.76          66.24
3                80.76          23.24
5                68.92          16.08
2                41.47          10.53
7                29.82          10.18
1                45.01           8.99
0                21.84           6.16
4                30.90           4.10

In [ ]:
collection_loss = spoilage.groupby("collection_id")["loss_amount_rs"].sum().mean()
print("Average Loss per Collection:", round(collection_loss,2))

Average Loss per Collection: 33.19

In [ ]:
enterprise_kpi = (
    df["gross_profit"].sum()
    - spoilage["loss_amount_rs"].sum()
) / sales["revenue"].sum()

print("Enterprise Performance Index:", round(enterprise_kpi,3))

Enterprise Performance Index: 0.204